"""Command line argument parsing."""

import sys
from argparse import (
    SUPPRESS,
    ArgumentDefaultsHelpFormatter,
    ArgumentParser,
    Namespace,
)
from inspect import cleandoc
from os.path import basename

from wg_lazy.consts import defaults


def parse_cmdline(
    argv: list[str] = sys.argv,
    prog: str = basename(sys.argv[0]),
    version: str = "x.y.z-unknown",
) -> Namespace:
    """Parse command line arguments and return them in a Namespace.

    Args:
        argv: Command line arguments
        prog: Program name
        version: Package version

    Returns:
        An argparse.Namespace instance.
    """
    parser = ArgumentParser(
        prog=prog, formatter_class=ArgumentDefaultsHelpFormatter
    )
    subparsers = parser.add_subparsers(
        dest="sub_command", metavar="sub-command", required=True
    )
    _setup_base_parser(parser, prog, version)
    _setup_new_sub_command(subparsers)
    _setup_add_sub_command(subparsers)
    _setup_rm_sub_command(subparsers)
    _setup_show_sub_command(subparsers)

    args_ns = parser.parse_args(argv[1:])
    return args_ns


def _setup_base_parser(parser: ArgumentParser, prog: str, version: str):
    """Set up base options."""
    parser.description = (
        f"{prog}: a simple WireGuard configuration file utility for wg-quick."
    )

    parser.add_argument(
        "-d",
        "--config-dir",
        default=defaults.CONFIG_DIR,
        help="base directory for configuration files",
    )
    parser.add_argument(
        "-i",
        "--interface-name",
        default=defaults.WG_INTERFACE,
        help="name of a new or existing WireGuard tunnel interface",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        dest="log_level",
        action="count",
        default=0,
        help="show log messages (repeat once to increase verbosity)",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"%(prog)s {version}",
    )
    parser.epilog = (
        "This tool uses its own configuration file (<interface-name>.json) "
        "to store tunnel settings which are not compatible with wg-quick. "
        "The configuration file is used to generate a file that is compatible "
        "with wg-quick."
    )


def _setup_new_sub_command(subparsers):
    """Set up the 'new' sub command."""
    new_parser = subparsers.add_parser(
        "new",
        help="create a new tunnel",
        argument_default=SUPPRESS,
        formatter_class=ArgumentDefaultsHelpFormatter,
    )

    new_parser.description = "Create a new tunnel and related configuration."
    new_parser.add_argument(
        "-a",
        "--endpoint",
        default=defaults.ENDPOINT,
        help="the server's public address; used in generated peer configs",
    )
    new_parser.add_argument(
        "-D",
        "--dns",
        default=defaults.DNS,
        help="default DNS for new peers",
    )
    new_parser.add_argument(
        "-p",
        "--listen-port",
        default=defaults.LISTEN_PORT,
        type=int,
        help="the server's WireGuard listen port",
    )
    new_parser.add_argument(
        "-F",
        "--force",
        action="store_true",
        help="overwrite existing configuration files if they exist",
    )


def _setup_add_sub_command(subparsers):
    """Set up the 'add' sub command."""
    add_parser = subparsers.add_parser(
        "add",
        help="add a peer to a tunnel and display it's new configuration",
        argument_default=SUPPRESS,
        formatter_class=ArgumentDefaultsHelpFormatter,
    )
    add_parser.description = "Add a peer to an existing tunnel configuration."
    add_parser.add_argument(
        "-n", "--peer-name", help="peer name (default: random uuid)"
    )
    add_parser.add_argument(
        "-s",
        "--save-private-key",
        action="store_true",
        help="save the peer's private key",
    )
    add_parser.add_argument(
        "-F",
        "--force",
        action="store_true",
        help="overwrite an existing peer with the same name if they exist",
    )
    add_parser.add_argument(
        "-o",
        "--output-format",
        choices=["qr", "-"],
        default="qr",
        type=str.lower,
        help="show a QR code for the new peer or print to stdout (-)",
    )
    add_parser.epilog = cleandoc(
        """
        A QR code is displayed by default so that a client can connect
        easily via the WireGuard app. For other systems, a configuration
        file can be generated by saving the output configuration (e.g.
        wg-lazy -i wg1 add -p laptop -o - > ~/peer.conf).

        A peer's configuration can be regenerated if the private key
        was saved using the "-s" option. This is not recommended as it
        can allow malicious actors to impersonate a peer if the host is
        compromised.
        """
    )


def _setup_rm_sub_command(subparsers):
    """Set up the 'rm' sub command."""
    rm_parser = subparsers.add_parser(
        "rm",
        help="delete a peer from an existing configuration",
        argument_default=SUPPRESS,
        formatter_class=ArgumentDefaultsHelpFormatter,
    )
    rm_parser.description = (
        "Delete a peer from an existing tunnel configuration. Confirmation "
        "is required by default."
    )
    rm_parser.add_argument(
        "-F",
        "--force",
        action="store_true",
        help="delete peer without confirmation",
    )
    rm_parser.add_argument(dest="peer_name", metavar="peer-name")


def _setup_show_sub_command(subparsers):
    """Set up the 'show' sub command."""
    subparsers.add_parser(
        "show",
        help="show interface and peer info",
        argument_default=SUPPRESS,
        formatter_class=ArgumentDefaultsHelpFormatter,
    )
